### ISSUE TITLE
Will it continue?

### ISSUE THREAD

**Issue by renanleandrof** [CottageLabs/edges#3]
Hello!

Are you guys planning to continue with this project or you gonna contribute with kibana and end it? 

Thanks

**Comment by emanuil-tolev** [comment]
Definitely continue, it's seeing a little bit of development now with hopefully more coming after July. It's replacing two older libraries, facetview and facetview2 (e.g. as can be seen on https://doaj.org/search - that's facetview2), but is far more modular and enables much better theming and wider range of functionality (e.g. visualisations with facet selections on the side).

We have used Kibana and it is very good, but it does not enable us to do what we want very easily. E.g. this library is currently being upgraded so it will support certain visualisations directly from CSV data - that can't be done in Kibana (obviously, due to the Elasticsearch focus, not necessarily a bad thing). We've also found it a bit .. clunky in terms of integrating it into other apps, although it's good on its own. 

And we mostly built web apps that need to do some/lots of other things in addition to visualisation for customers. E.g. see http://world-nuclear.org/information-library/facts-and-figures/reactor-database.aspx - both the facet search page of reactors, *and* individual reactor pages with table data, charts, and Google Maps (where data available) are built with this library. So just a different function to Kibana.

**Comment by renanleandrof** [comment]
This is exactly what i need and i couldn't do it with Kibana.

It is safe to use the actual version of Edges?

____________________________
Renan Leandro Ferreira
(61) 8436-0600
www.minhaio.com.br
"Sola Scriptura, Sola Gratia, Sola Fide, Solus Christus, Soli Deo Gloria!"

**Comment by richard-jones** [comment]
Yes, please do feel free to use the software.  We are lacking in documentation at the moment, so YMMV, but it has been deployed in production in a number of places, so we're fairly confident of it.

**Comment by dlwaticg** [comment]
This library looks fantastic and if my research is correct its the 3rd generation behind facetview and facetview2.  I am new to javascript and have tried to get a basic demo example up and running, but have not had been successful.  Does anyone have a example of a basic demo app using edges they could share?  Many Thanks.

**Comment by richard-jones** [comment]
We don't yet have an out-of-the-box demo, but there's some example usage here:

https://github.com/CottageLabs/edges/blob/develop/docs/example.js

You'll need your own ES instance full of data, and then you can hopefully get quickly to a working example by following the patterns in that file.
